name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          SLACK_MESSAGE: "Fail report by abc"
          SLACK_TITLE: "Fail report"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'fail_report.txt'
          exit-code: '1'
          severity: 'HIGH'

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_MESSAGE: "Fail report by abc"
          SLACK_TITLE: "ABC report"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
      # - name: Fail Report   # Corrected indentation here
      #   if: failure()
      #   uses: MeilCli/slack-upload-file@v4
      #   with:
      #     slack_token: ${{ secrets.SLACK_TOKEN }}
      #     channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
      #     content: 'file content'
      #     file_type: 'text'
      #     file_name: 'fail_report.txt'
      #     file_path: 'fail_report.txt'
      #     title: 'title of file'
      #     initial_comment: 'post by zeyu'

